### ISSUE TITLE
correct the branch

### ISSUE THREAD

**Issue by Haroenv** [ArnaudWeyts/blog#1]
currently your code is on the `master` branch and an empty `gh-pages` branch. This could be a mistake or maybe it's just not finished yet. Thought I'd let you know anyway.

**Comment by ArnaudWeyts** [comment]
it's not finished yet, working on setting it up with travis to push the builded _site directory to gh-pages, i'm aware :^)

**Comment by Haroenv** [comment]
in that case: https://blog.haroen.me/gems-on-github-pages

**Comment by ArnaudWeyts** [comment]
thanks!
